// ********************
// *******Readme*******
// ********************
// id 1 == hot
// id 2 == new
// id 3 == soon
// id 4 == คือไม่มีแท็ก
// ถ้ายังไม่เปิดดาวน์โหลด ตัวแปร "LinkLoad" ให้ใส่ javascript:void(0) แล้วเปิดคอมเม้น "alert"
var app = new Vue({
    el: '#PP_MobileGame',
    data: {
        games: [
            {
                id: "1",
                GameName: "Real Yulgang Mobile",
                Image: "https://media-web.playpark.com/poster-games/mobile/ryg.jpg",
                TagLine: "hot ",
                Type: "( MMORPG )",
                LinkId: "https://secure2.playpark.com/register/registSelect.aspx?game=PP",
                TypeId: "PlayID",
                DescId: "Play with PlayID Account",
                DescGame: "Real Yulgang Mobile ครบเครื่องทั้งภาพและเสียง ลิขสิทธิ์แท้จากเวอร์ชั่น PC ฉบับดั้งเดิมโดย MGAME สู่เกมมือถือ สนุกไร้ขีดจำกัด สานฝันวันวานตำนานเกม Yulgang",
                LinkSite: "https://realyulgang.playpark.com/",
                TextSite: "เข้าสู่เว็บไซต์",
                LinkLoad: "https://rym.playpark.com/th-th/playparkhome",
                  // alert: "alert('Download is Coming Soon');",
                TextLoad: "ดาวน์โหลด",
            },
            {
                id: "1",
                GameName: "TERA Classic SEA",
                Image: "https://media-web.playpark.com/poster-games/mobile/tera-classic.png",
                TagLine: "hot",
                Type: "( MMORPG )",
                LinkId: "https://secure2.playpark.com/register/registSelect.aspx?game=PP",
                TypeId: "PlayID",
                DescId: "Play with PlayID Account",
                DescGame: "เกมแนว MMORPG Open-World ที่พัฒนามาจากเกมชื่อดังสุดคลาสสิคอย่าง TERA Online ผจญภัยแบบไร้ขีดจำกัดกับกราฟฟิคที่สวยงามอลังการ ระบบต่างๆ ภายในเกมสุดตื่นตาตื่นใจ การปรับแต่งสกิล และสร้างคอมโบแบบไร้ขีดจำกัด สานต่อตำนาน TERA",
                LinkSite: "https://teraclassic.playpark.com/th-th/",
                TextSite: "เข้าสู่เว็บไซต์",
                LinkLoad: "https://teraclassic.playpark.com/download",
                // alert: "alert('Download is Coming Soon');",
                TextLoad: "ดาวน์โหลด",
            },

            {
                id: "3",
                GameName: "Streetballers",
                Image: "https://media-web.playpark.com/poster-games/mobile/sb.jpg",
                TagLine: "soon",
                Type: "( CASUAL )",
                LinkId: "https://secure2.playpark.com/register/registSelect.aspx?game=PP",
                TypeId: "PlayID",
                DescId: "Play with PlayID, AppleID, Facebook, Google Account",
                DescGame: "เกมมือถือแนวสตรีทบาสเก็ตบอล มันส์กับหลากหลายโหมดเกม, สกิลเฉพาะของตัวละคร, ชุดแฟชั่น และตกแต่งสนามได้ดั่งใจ ระเบิดความมันส์ ดังก์แป้นแตกพร้อมกันที่ StreetBallers!",
                LinkSite: "https://www.facebook.com/StreetBallersTHbyPlayPark",
                TextSite: "Facebook",
                LinkLoad: "javascript:void(0)",
                alert: "alert('Download is Coming Soon');",
                TextLoad: "ดาวน์โหลด",
            },
            {
                id: "3",
                GameName: "Tales of Fairy Empire",
                Image: "https://media-web.playpark.com/poster-games/mobile/tofe.png",
                TagLine: "soon",
                Type: "( Idle RPG )",
                LinkId: "https://secure2.playpark.com/register/registSelect.aspx?game=PP",
                TypeId: "PlayID",
                DescId: "Play with PlayID Account",
                DescGame: "เกมมือถือน้องใหม่แนว Idle ARPG ผจญภัยไปในโลกตัวละครแห่งเทพนิยายมากมาย จัดทีมพร้อมต่อสู้สร้างเรื่องราวใหม่ด้วยตัวคุณเอง!",
                LinkSite: "https://www.facebook.com/PlayPark.tofe/",
                TextSite: "Facebook",
                LinkLoad: "javascript:void(0)",
                alert: "alert('Download is Coming Soon');",
                TextLoad: "ดาวน์โหลด",
            },
            {
                id: "3",
                GameName: "The Legend of Savage",
                Image: "https://media-web.playpark.com/poster-games/mobile/los.png",
                TagLine: "soon",
                Type: "( MMORPG )",
                LinkId: "https://secure2.playpark.com/register/registSelect.aspx?game=PP",
                TypeId: "PlayID",
                DescId: "Play with PlayID Account",
                DescGame: "เซียนกระบี่สามภพ Mobile เกมมือถือแนวจีนกำลังภายใน แบบ OPEN WORLD MMORPG พร้อมสวมบทบาทเป็นยอดฝีมือจาก 4 เทพศาสตราวุธมันส์ไร้ขีดจำกัด",
                LinkSite: "https://los.playpark.com/",
                TextSite: "ลงทะเบียนล่วงหน้า",
                LinkLoad: "https://www.facebook.com/LOSPLAYPARK",
                // alert: "alert('Download is Coming Soon');",
                TextLoad: "Facebook",
            },
            {
                id: "4",
                GameName: "TS Online Mobile",
                Image: "https://media-web.playpark.com/poster-games/mobile/tsm.jpg",
                // TagLine: "soon",
                Type: "( MMORPG )",
                LinkId: "https://secure2.playpark.com/register/registSelect.aspx?game=PP",
                TypeId: "PlayID",
                DescId: "Play with PlayID Account",
                DescGame: "TS Online Mobile ผจญภัยป่วนมิติ กับปาโต้เยา และเรื่องราวยุคสามก๊ก สุดยอดเกม Turn-Based ในตำนานที่คุณคิดถึง จาก PlayPark.com",
                LinkSite: "https://tsonline.playpark.com/",
                TextSite: "เข้าสู่เว็บไซต์",
                LinkLoad: "http://onelink.to/pp-tsonline",
                // alert: "alert('Download is Coming Soon');",
                TextLoad: "ดาวน์โหลด",
            },
            {
                id: "4",
                GameName: "Nine Songs Of Fantasy",
                Image: "https://media-web.playpark.com/poster-games/mobile/nine-songs.jpg",
                // TagLine: "soon",
                Type: "( MMORPG )",
                LinkId: "https://secure2.playpark.com/register/registSelect.aspx?game=PP",
                TypeId: "PlayID",
                DescId: "Play with PlayID Account",
                DescGame: "Nine Songs of Fantasy : ตำนานเพลงรักเก้าสวรรค์ เกมโมบายล์แนวจีน MMORPG บนมือถือ ที่จะพาทุกคนเปิดตำนานผู้ถูกเลือกจากสวรรค์",
                LinkSite: "https://ninesongs.playpark.com/th-th/",
                TextSite: "เข้าสู่เว็บไซต์",
                LinkLoad: "https://ninesongs.playpark.com/th-th/",
                // alert: "alert('Download is Coming Soon');",
                TextLoad: "ดาวน์โหลด",
            },
           
            {
                id: "4",
                GameName: "Genki Heroes",
                Image: "https://media-web.playpark.com/poster-games/mobile/genki.png",
                // TagLine: "soon",
                Type: "( Sling Shot Game )",
                // LinkId: "javascript:void(0)",
                TypeId: "Other ID",
                DescId: "Play with Facebook, Google Account",
                DescGame: "อัพเกรดความมันส์จากเกมแนว slingshot พบเหล่าฮีโร่ชื่อดังมากมาย คอมโบสกิลและพลังระเบิดสุดอันตราย เหนือชั้นด้วยทักษะสกิลขั้นสูงที่มาพร้อมกับอนิเมชั่นสุดอลังการ",
                LinkSite: "http://genki.jollity.asia/en/",
                TextSite: "เข้าสู่เว็บไซต์",
                LinkLoad: "http://onelink.to/jt-genkiheroes",
                // alert: "alert('Download is Coming Soon');",
                TextLoad: "ดาวน์โหลด",
            },
            {
                id: "4",
                GameName: "ตำนานมังกรหยก M",
                Image: "https://media-web.playpark.com/poster-games/mobile/chm.jpg",
                // TagLine: "soon",
                Type: "( MMORPG )",
                LinkId: "https://secure2.playpark.com/register/registSelect.aspx?game=PP",
                TypeId: "PlayID",
                DescId: "Play with PlayID Account",
                DescGame: "ตำนานมังกรหยกM อภินิหารเกมจีนกำลังภายในแนว Turn-Base RPG จากนิยายกำลังภายในชื่อดังของ 'กิมย้ง' สู่เกมมือถือที่ยอดเยี่ยมที่สุดแห่งปี",
                LinkSite: "https://condorhero.playpark.com/",
                TextSite: "เข้าสู่เว็บไซต์",
                LinkLoad: "https://condorhero.playpark.com/th-th/",
                // alert: "alert('Download is Coming Soon');",
                TextLoad: "ดาวน์โหลด",
            },
          
            {
                id: "4",
                GameName: "หวงอี้ โมบาย HuangYi Mobile",
                Image: "https://media-web.playpark.com/poster-games/mobile/hym.jpg",
                // TagLine: "soon",
                Type: "( MMORPG )",
                LinkId: "https://secure2.playpark.com/register/registSelect.aspx?game=PP",
                TypeId: "PlayID",
                DescId: "Play with PlayID Account",
                DescGame: "เจาะเวลามังกรสะท้านภพ เกมมือถือแนวจีนกำลังภายในที่ผสมผสานกับโลกไซไฟแบบอนาคต Cross Platform เล่นสนุกทุกที่ มันส์ต่อเนื่อง ทั้งมือถือ และ PC เสน่ห์ทุกยุทธภพ มีครบที่นี่",
                LinkSite: "https://huangyimobile.playpark.com/",
                TextSite: "เข้าสู่เว็บไซต์",
                LinkLoad: "https://www.playpark.com/th-th/hym-pp-dl",
                // alert: "alert('Download is Coming Soon');",
                TextLoad: "ดาวน์โหลด",
            },
          
           
        ],
    },
    computed: {
        ordered: function () {
            return _.orderBy(this.games, ['id', 'GameName'], ['ASC', 'ASC']);
        },
    }
});